language: python
sudo: false
python:
  - "2.7.11"
before_install:
  - pip install -U pip==7
  - pip install flake8
  - flake8 remo
  - mysql -e 'create database remo character set utf8; SET @@GLOBAL.wait_timeout=28800;'
install:
  - npm install -g less
  - pip install coverage
  - bin/peep.py install -r requirements/dev.txt
script:
  - coverage run --source=remo manage.py test
after_success:
  - pip install coveralls
  - coveralls
