language: python
python:
  - "2.6"
before_script:
  - flake8 remo
before_install:
  - mysql -e 'create database remo character set utf8;'
  - git submodule update --init --recursive
install:
  - pip install -r requirements/compiled.txt
  - pip install -r requirements/dev.txt
  - pip install coverage
script:
  - python manage.py test --with-coverage --cover-erase --cover-package=remo
after_success:
  - pip install coveralls
  - coveralls
