language: python
sudo: false
python:
  - "2.7"
before_install:
  - pip install flake8
  - flake8 remo
  - mysql -e 'create database remo character set utf8; SET @@GLOBAL.wait_timeout=28800;'
  - git submodule update --init --recursive
install:
  - pip install -r requirements/dev.txt
script:
  - python manage.py test --with-coverage --cover-erase --cover-package=remo
after_success:
  - pip install coveralls
  - coveralls
